### ISSUE TITLE
Evidence, reporting, and %tower

### ISSUE THREAD

**Issue by hanfel-dovned** [urbit/Aegean#13]
We have the following types:

```
+$  locker  (map evidence @da)   ::  reported refs from friends
+$  evidence
  $:  mine=signature    ::  [p=@uvH q=ship r=life]
      %disavow
      =ref
      theirs=signature
      =entry
  ==
```

The vision here is for evidence to get sent around via the `%report` poke (which currently does nothing), mainly for the benefit of towers flagging malicious users.

This seems straightforward to implement (other than getting the poster's signature). Just need to sit down with tiller and figure out the spec a bit more.

**Comment by hanfel-dovned** [comment]
- Resolve ref again and then get the syg from the response

**Comment by hanfel-dovned** [comment]
[Making progress on this](https://github.com/urbit/Aegean/blob/master/desk/app/feed.hoon#L284). Still can't find the best function for the accuser to sign this with, and haven't been able to reverse engineer how Fine does it yet. `sign:as:acru:ames` can't be found when I try to import it.

**Comment by tiller-tolbus** [comment]
@hanfel-dovned the `acru:ames` in your subject is going to be just the type without any key information inside of it by default. You will have to get the private key from Jael. You can do this with either a subscription or a `.^` -- in this case a `.^` probably makes more sense. 

Once you have the private key, you can construct a `crub` core with `(nol:nu:crub:crypto key)`. This crub core can sign messages with `sign:as:my-crub` per the [docs](https://docs.urbit.org/language/hoon/reference/cryptography), but you may actually want to use `sigh:as:my-crub` in this case since you would not prefer to `jam` the result. I was not super satisfied with the docs for these functions, so I recommend at least having a gander at [the source](https://github.com/urbit/urbit/blob/develop/pkg/arvo/sys/zuse.hoon#L1442).

**Comment by hanfel-dovned** [comment]
@tiller-tolbus Cool, I think I'm making more progress with this. I'm getting a `%arvo-response! /j/app/life/hoon/~ler` on the life scry; before I debug further, I should ask: do fakeships have a `life` and key, or should I build this out on comets?

**Comment by hanfel-dovned** [comment]
Might need to tweak some stuff here for [411 and encrypted scry](https://github.com/urbit/urbit/releases/tag/411k-rc0). Maybe punt until after shrubbery.
